### ISSUE TITLE
Meta-issue - 1.0-RC1

### ISSUE THREAD

**Issue by alexarchambault** [alexarchambault/coursier#206]
Remaining issues before 1.0-RC1:
- [ ] Order the result artifacts (https://github.com/alexarchambault/coursier/issues/233)
- [ ] Print evictions from the SBT plugin and the CLI tools. Have a look at `evicted` in the SBT plugin too (https://github.com/alexarchambault/coursier/issues/170).
- [ ] Fail early if some checksum verifying failed (https://github.com/alexarchambault/coursier/issues/157).
- [ ] Have a better string representation of the internal repositories, in the printed repository list, with the SBT plugin, have the corresponding errors be nice too. (Includes https://github.com/alexarchambault/coursier/issues/182.)
- [X] Add support for `excludeDependencies` in SBT plugin (https://github.com/alexarchambault/coursier/issues/199)
- [X] Add support for `from` URL of `ModuleID` in SBT plugin (https://github.com/alexarchambault/coursier/issues/196)
- [X] Fix possible remaining issue with `update-changing` mode (https://github.com/alexarchambault/coursier/issues/154).
- [X] Add support for authentication (includes https://github.com/alexarchambault/coursier/issues/147).
- [X] Follow the `mavenCompatible` flag of repositories coming from SBT (https://github.com/alexarchambault/coursier/issues/146)
- [x] Print clearer errors from the SBT plugin (https://github.com/alexarchambault/coursier/issues/123)
- [X] use SBT logging wherever possible (https://github.com/alexarchambault/coursier/issues/119)
- [x] Add support for TTL for changing artifacts

See also https://github.com/ensime/ensime-server/pull/1312#issuecomment-201564050
- [ ] Discard repositories missing some particular artifacts, during resolution (https://github.com/alexarchambault/coursier/issues/200)
- [X] reduce logging even more by default in non interactive mode (fixed by https://github.com/alexarchambault/coursier/pull/217)
- [ ] reduce logging even more than that? (https://github.com/alexarchambault/coursier/issues/244)
- [X] ensure the `update-changing` mode is fine (still experiencing issues at the build project level - tries to update everything - and in ensime-server - tries to update some non-snapshot versions, https://github.com/alexarchambault/coursier/issues/154)
- [X] Possible Windows issues (https://github.com/alexarchambault/coursier/issues/207, https://github.com/alexarchambault/coursier/issues/208)

Maybe
- [ ] Refactor a bit the parts that involve reflection (https://github.com/alexarchambault/coursier/issues/144).
- [ ] Add integration tests for the launcher (https://github.com/alexarchambault/coursier/issues/115)
- [X] Add unit / integration tests for the SBT plugin (https://github.com/alexarchambault/coursier/issues/113, https://github.com/alexarchambault/coursier/issues/114)
- [ ] Factor artifact files to reduce disk occupation, pick things from `~/.ivy2/cache` if they have the expected checksum (https://twitter.com/alxarchambault/status/707962267967614978).
- [ ] Use platform-specific directory for the cache, if it already exists (https://github.com/alexarchambault/coursier/issues/204).
- [ ] Add support for `latest.*` versions (https://github.com/alexarchambault/coursier/issues/209).
- [X] Allow to print trees or graphs of dependencies (https://github.com/alexarchambault/coursier/issues/215).

**Comment by alexarchambault** [comment]
Now deprecated. (Handled with simple github milestones.)
